name: Continuous Integration

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  tests-and-lints:
    uses: ./.github/workflows/tests-and-lints-template.yaml
    secrets:
      eth_rpc_url: ${{ secrets.ETH_RPC_URL }}
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}

