name: Promote to production

on:
  workflow_dispatch:
    inputs:
      image_tag:
        required: true
        type: string
        description: Image tag for production deployment

jobs:
  promote-to-production:
    uses: propeller-heads/ci-cd-templates/.github/workflows/promote-to-production.yaml@main
    with:
      image_tag: ${{ inputs.image_tag }}
      image_name: propeller-searcher
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
