name: Maintenance Release; build and push

on:
  push:
    branches:
      - release/*

jobs:
  tests-and-lints:
    uses: ./.github/workflows/tests-and-lints-template.yaml
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      infura_api_key: ${{ secrets.INFURA_API_KEY }}

  check-release:
    uses: propeller-heads/ci-cd-templates/.github/workflows/release-v2.yaml@main
    with:
      args: --dry-run --no-ci
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}

  release:
    needs:
      - tests-and-lints
      - check-release
    if: needs.check-release.outputs.verify_release_version != ''
    uses: propeller-heads/ci-cd-templates/.github/workflows/release-v2.yaml@main
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}

  build-and-push:
    needs:
      - release
    if: needs.release.outputs.next_release_version != ''
    uses: propeller-heads/ci-cd-templates/.github/workflows/build-and-push-docker-image.yaml@main
    permissions:
      id-token: write
      contents: read
    with:
      image_tag: ${{ needs.release.outputs.next_release_version }}
      image_name: propeller-searcher
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
